<a href="https://colab.research.google.com/github/Suhrobjonibodullayev/ML-Learning-Journey/blob/main/02_numpy_basics/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

Ustunligi:
1. Tez ishlashida C dasturlash tilida yozilganligi sababli

2. N dimentional Array - bir vaqtning o'zida malumotlar toplamining barcha elementlari ustida amallar bajara olshida.

https://numpy.org/devdocs/user/absolute_beginners.html$0

In [1]:
import numpy as np

In [7]:
x2 = np.array([[1, 2, 3],
              [4, 5, 6]])

x2.shape # (rows,columns) qator va ustunlar soni
np.shape(a)

np.ndim(a) # 2d arrayning o'lchami

np.size(a) # elementlar soni

x2.dtype # malumot turini aniqlash
x2.astype(np.float64) # malumot turini o'zgartirish

array([[1., 2., 3.],
       [4., 5., 6.]])

**Arrayni Yaratish usullari**

In [3]:
np.zeros((2,4)) # barcha elementlari 0 ga teng bo'lgan shape(2,4) 2darray

np.ones((2,4)) # barcha elementlari 1 ga teng bo'lgan shape(2,4) 2darray
np.ones((3, 5), dtype=float)

np.full((3, 5), 3.14)

np.arange(4,20,2).reshape(2,4) # 4 bilan boshlanib 20 gacha bo'lgan qadamlari 2 teng 2d array

c = np.random.rand(2,4) # o'lchami(2,4) teng . (0-1) oralig'idagi o'nlik sonlar

np.random.randn(2,4) # o'lchami(2,4) teng . (+,-) o'nlik sonlar

np.random.normal(0, 1, (3, 3)) # values with mean 0 and standard deviation 1

np.random.randint(5,size=(2,4)) # max 5 bo'lgan butun sonlar
np.random.randint(0, 10, (3, 3))

# Create a 3x3 identity matrix
np.eye(3)

np.empty(3)

np.linspace(0, 10, num=5) # 0 dan 10 gacha 5 qismga ajratilgan

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
x1=np.arange(10)

# x[start:stop:step]

x1[3:5] # index 0 dan boshlanadi . 3 dan 5 gacha kesish , 5 kirmaydi.

x1[::2]  # every second element
x1[1::2]  # every second element, starting at index 1

x1[4::-2]  # every second element from index 4, reversed

b[:] # to'liq nusxa olish

x2[:2, :3]  # first two rows & three columns

a[:1,1:] # [qator,ustun] 2d arrayda kesish

x2[:3, ::2]  # three rows, every second column

x2[::-1, ::-1]  # all rows & columns, reversed

reversed_arr = np.flip(x2) # teskariga aylantiradi

x2[0]  # equivalent to x2[0, :]

x2_sub_copy = x2[:2, :2].copy()


In [10]:

A = np.arange(6).reshape(2,3)
A #(2,3)
A.T # (3,2) -- > A.swapaxes(1,0)


array([[0, 3],
       [1, 4],
       [2, 5]])

In [11]:
np.sqrt(A) # array barcha elementlarini kv ildizini hisoblaydi
np.square(A) # array barcha elementlarini kvadratini hisoblaydi

q,b = np.modf(c) # qoldiq va butun qili aloxida arrayga saqlaydi

np.sign(A) # manfiy elementlar (-1) musbat elementlar (+1) qilib saqlaydi

np.isnan(A) # NaN qiymatlar(True), yo'q bo'lsa (False)


array([[False, False, False],
       [False, False, False]])

In [12]:
np.add(A,a) # A + A.T
np.subtract(A,a) # A - A.T

np.min(A) # minimum qiymatlarni qaytaradi
np.max(A) # maxsimum qiymatlarni qaytaradi

np.sum(A) # yig'indini hisoblaydi
np.mean(A) # o'rtacha qiymatni hisoblaydi

np.sort(A) # tartiblash kichikdan kattaga
-np.sort(-A) # teskari tartiblash kattadan kichikga
A[::-1] # teskari tartiblash kattadan kichikga

# abs(x). np.absolute(x) np.exp(x)  np.exp2(x)

array([[3, 4, 5],
       [0, 1, 2]])

In [13]:
np.unique(a) # takrorlanmas qiymatlarni qaytaradi

np.in1d(A,a) # A ning elementlarini a da borligini tekshiradi

np.setdiff1d(A,a) # A ning a dagi takrorlanmas qiymatlarini qaytaradi

np.nonzero(A) # 0 ga teng bo'lmagan index elementlarini qaytaradi

/tmp/ipykernel_718/4273879103.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(A,a) # A ning elementlarini a da borligini tekshiradi


(array([0, 0, 1, 1, 1]), array([1, 2, 0, 1, 2]))

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b)) # 2 ta arrayni birlashtirish

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0) # ustun bo'yicha birlashtirish

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

five_up = (a > 5) | (a == 5)
print(five_up)

c = a[(a > 2) & (a < 11)]
print(c)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 3  4  5  6  7  8  9 10]


In [16]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

reversed_arr = np.flip(arr) # teskariga aylantiradi

arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [18]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

x.flatten() # --> 1D array
a2 = x.ravel() # --> 1D array

NumPy - Statistical Functions

NumPy - Sort, Search & Counting Functions

https://www.tutorialspoint.com/numpy/numpy_sort_search_counting_functions.htm

In [19]:
import numpy as np

a = np.arange(-8, 10)

# Qiymatlarni 5 dan 15 gacha cheklash
clipped_array = np.clip(a, 5, 15)
print('Cheklangan massiv:', clipped_array)

# Musbat sonlarni 1 ga, manfiylarini -1 ga o'zgartirish np.where(condition, x, y)  # agar condition True bo‘lsa x, yo‘q bo‘lsa y

new_array = np.where(a > 0, 1, -1)
print('Yangilangan massiv:', new_array)

# Massivni teng qismlarga bo‘lish
split_arrays = np.split(a, 3)
print('Bo‘lingan massivlar:', split_arrays)

Cheklangan massiv: [5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 7 8 9]
Yangilangan massiv: [-1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1  1  1]
Bo‘lingan massivlar: [array([-8, -7, -6, -5, -4, -3]), array([-2, -1,  0,  1,  2,  3]), array([4, 5, 6, 7, 8, 9])]


In [20]:
import numpy as np

# Tasodifiy massivlar yaratish
a = np.random.rand(10)
b = np.random.rand(10)

# Korrelyatsiya koeffitsienti
correlation = np.corrcoef(a, b)
print('Korrelyatsiya koeffitsienti:', correlation)

Korrelyatsiya koeffitsienti: [[1.         0.48239337]
 [0.48239337 1.        ]]


In [21]:
import numpy as np

# Ikkita vektor yaratish
v1 = np.array([1, 2])
v2 = np.array([3, 4])

# Tashqi ko‘paytmani hisoblash
outer_product = np.outer(v1, v2)
print('Tashqi ko‘paytma:', outer_product)

# Ichki ko‘paytmani hisoblash
inner_product = np.inner(v1, v2)
print('Ichki ko‘paytma:', inner_product)

# Massivni cheklash
a = np.array([-10, 0, 5, 15])
clipped_array = np.clip(a, 0, 10)
print('Cheklangan massiv:', clipped_array)

Tashqi ko‘paytma: [[3 4]
 [6 8]]
Ichki ko‘paytma: 11
Cheklangan massiv: [ 0  0  5 10]


### np.where 3-usulda ishlaydi

In [22]:
import numpy as np

#index olish
a = np.array([0, 1, 2, 0])
np.where(a > 0)  # (array([1, 2]),)

# Shart asosida tanlash:
np.where(a > 0, 'yes', 'no')  # ['no' 'yes' 'yes' 'no']

b = np.array([[1, 2], [3, 0]])
np.where(b == 0, -1, b)  # [[1 2] [3 -1]]

# labels = np.where(total_scores >= 320, 'A',
         # np.where(total_scores >= 250, 'B', 'C'))

array([[ 1,  2],
       [ 3, -1]])

In [23]:
import numpy as np

np.random.seed(0)
grades = np.random.randint(40, 101, size=(10, 4))  # 10 talaba, 4 fan
subjects = ['Math', 'Physics', 'History', 'English']
normalized = grades / 100
mean_scores = np.mean(grades, axis=0, keepdims=True)
median_scores = np.median(grades, axis=0, keepdims=True)
total_scores = np.sum(grades, axis=1, keepdims=True)
best_subject_idx = np.argmax(grades, axis=1)
labels = np.where(grades >= 90, 'A',
         np.where(grades >= 80, 'B',
         np.where(grades >= 70, 'C',
         np.where(grades >= 60, 'D', 'F'))))

print("Baholar:\n", grades)
print("Normallashtirilgan:\n", normalized)
print("O‘rtacha baholar:\n", mean_scores)
print("Umumiy ballar:\n", total_scores)
print("Eng yaxshi fan indeksi:\n", best_subject_idx)
print("Baholar harfi:\n", labels)

Baholar:
 [[84 87 93 40]
 [43 99 43 79]
 [49 59 61 90]
 [76 63 46 64]
 [64 52 98 41]
 [78 79 63 86]
 [64 57 77 65]
 [53 48 49 60]
 [91 56 91 45]
 [55 87 40 58]]
Normallashtirilgan:
 [[0.84 0.87 0.93 0.4 ]
 [0.43 0.99 0.43 0.79]
 [0.49 0.59 0.61 0.9 ]
 [0.76 0.63 0.46 0.64]
 [0.64 0.52 0.98 0.41]
 [0.78 0.79 0.63 0.86]
 [0.64 0.57 0.77 0.65]
 [0.53 0.48 0.49 0.6 ]
 [0.91 0.56 0.91 0.45]
 [0.55 0.87 0.4  0.58]]
O‘rtacha baholar:
 [[65.7 68.7 66.1 62.8]]
Umumiy ballar:
 [[304]
 [264]
 [259]
 [249]
 [255]
 [306]
 [263]
 [210]
 [283]
 [240]]
Eng yaxshi fan indeksi:
 [2 1 3 0 2 3 2 3 0 1]
Baholar harfi:
 [['B' 'B' 'A' 'F']
 ['F' 'A' 'F' 'C']
 ['F' 'F' 'D' 'A']
 ['C' 'D' 'F' 'D']
 ['D' 'F' 'A' 'F']
 ['C' 'C' 'D' 'B']
 ['D' 'F' 'C' 'D']
 ['F' 'F' 'F' 'D']
 ['A' 'F' 'A' 'F']
 ['F' 'B' 'F' 'F']]


In [24]:
import numpy as np

# Har bir qatorda: [ID, Matematika, Fizika, Ingliz tili]
grades = np.array([
    [101, 78, 65, 80],
    [102, 45, 50, 48],
    [103, 90, 88, 92],
    [104, 60, 70, 55],
    [105, 30, 40, 35]
])
# Faqat baholarni ajratamiz (ID ni olib tashlaymiz)
scores = grades[:, 1:]

# Har bir talaba bo'yicha o'rtacha baho
avg_scores = scores.mean(axis=1, keepdims=True)

# Yangi ustun sifatida qo'shamiz
grades_with_avg = np.concatenate((grades, avg_scores), axis=1)
print(grades_with_avg)

# O'rtacha baho 60 dan yuqori bo'lsa - Pass, aks holda - Fail
status = np.where(avg_scores >= 60, "Pass", "Fail")

# Talaba ID + Status ko'rinishida chiqaramiz
result = np.concatenate((grades[:, :1], status), axis=1)
print(result)

subject_avg = scores.mean(axis=0)
print("Fanlar bo'yicha o'rtacha baholar:", subject_avg)

[[101.          78.          65.          80.          74.33333333]
 [102.          45.          50.          48.          47.66666667]
 [103.          90.          88.          92.          90.        ]
 [104.          60.          70.          55.          61.66666667]
 [105.          30.          40.          35.          35.        ]]
[['101' 'Pass']
 ['102' 'Fail']
 ['103' 'Pass']
 ['104' 'Pass']
 ['105' 'Fail']]
Fanlar bo'yicha o'rtacha baholar: [60.6 62.6 62. ]


In [25]:
import numpy as np

# Ma'lumotlar
days = np.array(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])
distances = np.array([5.2, 6.0, 0.0, 5.5, 4.8, 7.2, 3.0])  # km
times = np.array([30, 35, 0, 32, 28, 40, 20])  # minutes

# 1. O'rtacha tezlik (km/min)
speeds = np.divide(distances, times, out=np.zeros_like(distances), where=times!=0)

# 2. 5 km dan ko'p yugurilgan kunlar
long_runs = np.where(distances > 5)[0]

# 3. Shape saqlab, har kunlik km/soat ni topamiz
speeds_kph = speeds * 60
speeds_kph = np.expand_dims(speeds_kph, axis=1)

# 4. Har bir kun holati: "Rest" (0 km), "Short" (≤5 km), "Long" (>5 km)
run_type = np.where(distances == 0, "Rest",
            np.where(distances > 5, "Long", "Short"))

# 5. Haftalik umumiy statistika
total_distance = distances.sum()
avg_speed = np.mean(speeds_kph[distances > 0])  # faqat yugurilgan kunlar
max_day = days[np.argmax(distances)]

# Natijalar
print("Tezliklar (km/soat):\n", speeds_kph)
print("5km+ kunlar:", days[long_runs])
print("Har kun holati:", run_type)
print("Umumiy masofa:", total_distance, "km")
print("O‘rtacha tezlik:", round(avg_speed, 2), "km/h")
print("Eng ko‘p yugurilgan kun:", max_day)

Tezliklar (km/soat):
 [[10.4       ]
 [10.28571429]
 [ 0.        ]
 [10.3125    ]
 [10.28571429]
 [10.8       ]
 [ 9.        ]]
5km+ kunlar: ['Mon' 'Tue' 'Thu' 'Sat']
Har kun holati: ['Long' 'Long' 'Rest' 'Long' 'Short' 'Long' 'Short']
Umumiy masofa: 31.7 km
O‘rtacha tezlik: 10.18 km/h
Eng ko‘p yugurilgan kun: Sat


1. NumPy nima?
Python uchun tez, moslashuvchan massiv kutubxonasi.
Asosiy obyekti – ndarray (N-dimensional array).
C asosida yozilgan, juda tez ishlaydi.

2. ndarray va Python ro'yxati (list) o'rtasidagi farq?

| xususiyat        | `ndarray`                | `list`                  |
| ---------------- | ------------------------ | ----------------------- |
| Hajm             | Ruxsat etilmaydi         | Har xil o'lchamli       |
| Tezlik           | Tez (C bilan bog'langan) | Sekin (for loop orqali) |
| Vektorli amallar | Mavjud                   | Yo'q (loop kerak)       |
| Xotira           | Kam foydalanadi          | Ko'proq foydalanadi     |

3. Broadcasting nima?
Turli o'lchamdagi arraylar ustida amallar bajarish usuli.
Masalan:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(a + b)

4. axis parametri nima qiladi?
Operatsiyani qaysi yo’nalishda bajarilishini belgilaydi.

a.sum(axis=0)  # ustun bo'yicha
a.sum(axis=1)  # qator bo'yicha

5. np.where qanday ishlaydi?
Shartga qarab qiymat tanlaydi:

a = np.array([1, 6, 3])
np.where(a > 5, 'High', 'Low')

6. keepdims=True nima qiladi?
Operatsiyadan so'ng shaklni saqlaydi (broadcast uchun qulay):

a = np.array([[1, 2], [3, 4]])
a.sum(axis=1, keepdims=True)

7. ufunc nima?
Universal funksiyalar, vektorli amallarni tez bajaradi.
Misol: np.sqrt([1, 4, 9])  # [1. 2. 3.]

8. reshape, ravel, flatten farqi nima?
reshape: yangi shaklga o‘zgartiradi (ko‘pincha view).
ravel: tekislash (view, imkon bo‘lsa).
flatten: tekislash (yangi nusxa yaratadi).

9. NaN bilan ishlash qanday?

np.isnan(a)
np.nanmean(a)
np.nan_to_num(a)

10. Indexing turlari:
Boolean indexing:

a = np.array([1, 2, 3, 4])
a[a > 2]  # [3 4]

Fancy indexing:

a[[0, 2]]  # [1 3]